// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/RetroFilmCrowdfundingApp-6Pdd5c/App.tsx": () => import("../components/mockups/templates/RetroFilmCrowdfundingApp-6Pdd5c/App.tsx"),
  "./components/mockups/templates/RetroFilmCrowdfundingApp-W7boSe/App.tsx": () => import("../components/mockups/templates/RetroFilmCrowdfundingApp-W7boSe/App.tsx"),
  "./components/mockups/templates/RetroFilmCrowdfundingApp-arPR7h/App.tsx": () => import("../components/mockups/templates/RetroFilmCrowdfundingApp-arPR7h/App.tsx")
};
